### PR TITLE
Improvements for demo app

### PR DESCRIPTION
**Pull request by chrisbowley**
Fixed crash on image capture (removed dispatch) 
Use higher quality capture preset

### CODE REVIEW

**Comment by chrisbowley** [comment]
@hansemannn if this all looks good can you merge these changes? Then we can get the demo app out :)

**Review by hansemannn — APPROVED** [review]
Looks awesome, thx!

**Comment by hansemannn** [comment]
@chrisbowley Yes, merging now. Just returned from vacation 😊

**Comment by chrisbowley** [comment]
@hansemannn tsk shouldn't be allowed 😉. Thanks!

**Pull request merged**
